---
title: "wk4_lab"
name: Yiping Li
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, install libraries}
library(tidyverse)
library(data.table)
```

#Step1, readin data
```{r}
if (!file.exists("met_all.gz"))
  download.file(
    url = "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
    destfile = "met_all.gz",
    method   = "libcurl",
    timeout  = 60
    )
met <- data.table::fread("met_all.gz")
```
#Step 2, prep data
```{r}
#Remove temperatures less than -17C and change elev 9999 to missing value code
met <- met[temp > -17][elev == 9999.0, elev:=NA]

#Generate a date variable using the functions as.Date() (hint: You will need the following to create a date paste(year, month, day, sep = "-")).
met <- met[ , ymd := as.Date(paste(year, month, day, sep = "-"))]

#Using the data.table::week function, keep the observations of the first week of the month.
met [, table(week(ymd))]
met <- met[week(ymd)==31]

#check above step
nrow(met)

#Compute the mean by station of the variables temp, rh, wind.sp, vis.dist, dew.point, lat, lon, and elev. (can check max by replacing mean to max) 
met_avg <- met[, .(
  temp = mean(temp, na.rm=T), 
  rh = mean(rh, na.rm=T), 
  wind.sp = mean(wind.sp, na.rm=T), 
  vis.dist = mean(vis.dist, na.rm=T), 
  dew.point = mean(dew.point, na.rm=T), 
  lat = mean(lat, na.rm=T), 
  lon = mean(lon, na.rm=T), 
  elev = mean(elev, na.rm=T)
), by = "USAFID"]

#Create a region variable for NW, SW, NE, SE based on lon = -98.00 and lat = 39.71 degrees
#Create a categorical variable for elevation as in the lecture slides

```

